import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import NextTopLoader from 'nextjs-toploader';
import Providers from '@/components/providers';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <NextTopLoader color='#106A64' showSpinner={false} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
